-- AlterTable
ALTER TABLE "BusinessSolution" ALTER COLUMN "img" SET NOT NULL,
ALTER COLUMN "img" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "News" ALTER COLUMN "img" SET NOT NULL,
ALTER COLUMN "img" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "SubCategory" ALTER COLUMN "img" SET NOT NULL,
ALTER COLUMN "img" SET DATA TYPE TEXT;
